version: '3.1'

services:
  php:
    image: php:7.1-apache
    volumes:
      - "./.data/db:/var/lib/mysql"
      # Place mysql dump in mysql folder for automatic import
      - "./mysql:/docker-entrypoint-initdb.d"
    restart: always
    volumes:
      - "./:/var/www/html"
    ports:
      - "8000:80"
